version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY}/sentinel-backend:${IMAGE_TAG}
    container_name: sentinel-backend-staging
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - DATABASE_URL=jdbc:postgresql://${DB_ENDPOINT}:5432/sentinel
      - REDIS_HOST=${REDIS_ENDPOINT}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    image: ${ECR_REGISTRY}/sentinel-frontend:${IMAGE_TAG}
    container_name: sentinel-frontend-staging
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://${STAGING_DOMAIN}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: sentinel-staging-network